<?php

function utilities_isJson($string) {
    json_decode($string);
    return (json_last_error() == JSON_ERROR_NONE);
}

function dbg($identifier, $variable) {

    $backtrace = debug_backtrace(1);
    echo "<br><h4>Debug: $identifier</h4>";
    echo "<pre>";
    print_r($variable);
    echo "</pre>";
    echo "<br><i>". $backtrace[1]['function'] . "</i>";
    echo "<hr/>";
    
}

function utilities_find_parent($array, $needle, $parent = null) {
    foreach ($array as $key => $value) {
        if (is_array($value)) {
            $pass = $parent;
            if (is_string($key)) {
                $pass = $key;
            }
            $found = utilities_find_parent($value, $needle, $pass);
            if ($found !== false) {
                return $found;
            }
        } else if ($key === 'id' && $value === $needle) {
            return $parent;
        }
    }

    return false;
}

function utilities_recursive_array_search($needle,$haystack) {
    foreach($haystack as $key=>$value) {
        $current_key=$key;
        if($needle===$value OR (is_array($value) && utilities_recursive_array_search($needle,$value) !== false)) {
            return $current_key;
        }
    }
    return false;
}
?>