<?php

function smart_auth_user() {
    if ($_SERVER['HTTP_AUTHORIZATION']) {
        list($username, $password) = explode(':', base64_decode(substr($_SERVER['HTTP_AUTHORIZATION'], 6)), 2);
        //$username = 'denncath';
        //$password = 'denncath';
                
        if ($username) {
            if ($uid = user_authenticate($username, $password)) {
                global $user;
                $user = user_load($uid);

                $login_array = array('name' => $username);
                user_login_finalize($login_array);
            }
        }
    }

    if (user_is_logged_in()) {
        return true;
    }

    header('HTTP/1.0 403 Forbidden');
}

function smart_auth_get_unit() {
    global $user;
    
    if (isset($_POST[variable_get('inc_json_UNIT')])) {
        list($key, $secret) = explode(':', base64_decode($_POST[variable_get('inc_json_UNIT')]), 2);
    }
    $key = "abcd1234";
    $secret = "abcd";
    
    dbg("Identifying unit as: " . $user->name, "" );
    dbg("Searching key:" . $key . " - " . $secret, "" );

    $nid = smart_unit_get_nid_by_auth($key, $secret);

    if ($nid) {
        return $nid;
    }
    
    header('HTTP/1.0 403 Forbidden');
}
